build_tag_release:
  image: greenaddress/android@sha256:5ebd8c5b78e6cbd0fca507c920af095e05c7b2f43daea0a92597e3360f30e50c
  artifacts:
    name: "greenbits-release-$CI_COMMIT_REF_NAME"
    expire_in: 1 hour
    when: on_success
    paths:
    - app/build/outputs/apk/*/release/*.apk
    - app/build/outputs/mapping/*/release/mapping.txt
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./app/fetch_libwally_binaries.sh
    - ./gradlew assembleProductionRelease assembleBtctestnetRelease assembleProduction_21Release assembleBtctestnet_21Release

build_tag_osx_release:
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - ./app/fetch_libwally_binaries.sh
    - ./gradlew assembleProductionRelease assembleBtctestnetRelease assembleProduction_21Release assembleBtctestnet_21Release

package_release:
  tags:
    - garelease
  stage: deploy
  artifacts:
    expire_in: 14 days
    paths:
    - app/build/outputs/*
    when: on_success
  script: cd $CI_PROJECT_DIR/app/build/outputs/apk && /opt/process_release
  dependencies:
  - build_tag_release
