language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: docker run -v $PWD:/gb greenaddress/android@sha256:da4344cf07badff07f3967ac2d82bf75acd925ffbba2d8f9e3cc78343d7cbe23 /bin/sh -c "cd /gb && ./app/fetch_libwally_binaries.sh && ./gradlew --project-dir=bitcoinj/tools build && ./gradlew assembleProductionRelease"
    - os: osx
      osx_image: xcode8.3
      env:
        - ANDROID_HOME=/Users/travis/opt
        - SDK_FILENAME=sdk-tools-darwin-3859397.zip
      install:
        - mkdir -p $HOME/opt
        - cd $HOME/opt && curl -sSO https://dl.google.com/android/repository/${SDK_FILENAME} && unzip -qq ${SDK_FILENAME} &> /dev/null
        - brew update &> /dev/null
        - brew install swig gnu-sed pkg-config &> /dev/null
        - yes | $HOME/opt/tools/bin/sdkmanager "tools" "platform-tools" &> /dev/null
        - yes | $HOME/opt/tools/bin/sdkmanager "build-tools;27.0.3" &> /dev/null
        - yes | $HOME/opt/tools/bin/sdkmanager "platforms;android-27" &> /dev/null
        - yes | $HOME/opt/tools/bin/sdkmanager "extras;android;m2repository" "extras;google;m2repository" &> /dev/null
      script:
        - export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
        - cd $HOME/build/greenaddress/GreenBits/app && ./fetch_libwally_binaries.sh
        - cd $HOME/build/greenaddress/GreenBits && ./gradlew assembleProductionDebug
    - services:
        - docker
      script: docker run -v $PWD:/gb greenaddress/android@sha256:da4344cf07badff07f3967ac2d82bf75acd925ffbba2d8f9e3cc78343d7cbe23 /bin/sh -c "cd /gb && ./app/fetch_libwally_binaries.sh && ./gradlew --project-dir=bitcoinj/tools build && ./gradlew assembleBtctestnetRelease"
    - services:
        - docker
      script: docker run -v $PWD:/gb greenaddress/android@sha256:da4344cf07badff07f3967ac2d82bf75acd925ffbba2d8f9e3cc78343d7cbe23 /bin/sh -c "cd /gb && ./app/fetch_libwally_binaries.sh && ./gradlew --project-dir=bitcoinj/tools build && ./gradlew assembleElementsregtestRelease"
